---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ZooGVT

<!-- badges: start -->
<!-- badges: end -->

The goal of ZooGVT is to ...

## Installation

You can install the released version of ZooGVT from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("ZooGVT")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("Tsmnbx/ZooGVT")
```
## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(ZooGVT)
## basic example code
```


```{r cars}

```



```{r pressure, echo = FALSE}

```

``` r
Acknowledgements
```

This package was developed as part of an assessment for 2020 BCB410H: Applied Bioinformatics, University of Toronto, Toronto,CANADA.
